trigger: none

pr: none 

 

name: ServerInstallation- $(Rev:r)

parameters: 

- name: environmentTag

  displayName: Environment

  type: string

  default: tam

  values:

  - tam

  - dev

   

stages:

- stage: Nginx Stage

  dependsOn: []

  jobs:

  - deployment: 'tomcatInstallation'

    environment:

      name: Test_Environment

      resourceType: 'VirtualMachine'

      tags: nginx

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u "51575958-5da5-4ff6-8bc3-20519ae64e29" -p "SyuG47LO-3.v3Ax.iUu-qggxe8--CxOIeV" --tenant "8b87af7d-8647-4dc7-8df4-5f69a2011bb5"
                  key=$(az storage account keys list -g "utkarsh-rg" -n "storageaccountgeekplus" --query [0].value -o tsv)
                  az storage file download --share-name "geekplus" --path "nginx/test.json" --account-key $key --account-name "storageaccountgeekplus" --dest .
                  ls 
                  pwd    
- stage: Tomcat Stage

  dependsOn: []

  jobs:

  - deployment: 'tomcatInstallation'

    environment:

      name: Test_Environment

      resourceType: 'VirtualMachine'

      tags: nginx

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u "51575958-5da5-4ff6-8bc3-20519ae64e29" -p "SyuG47LO-3.v3Ax.iUu-qggxe8--CxOIeV" --tenant "8b87af7d-8647-4dc7-8df4-5f69a2011bb5"
                  key=$(az storage account keys list -g "utkarsh-rg" -n "storageaccountgeekplus" --query [0].value -o tsv)
                  az storage file download --share-name "geekplus" --path "nginx/test.json" --account-key $key --account-name "storageaccountgeekplus" --dest .
                  ls 
                  pwd    