trigger: none

pr: none 

 

name: ServerInstallation- $(Rev:r)

stages:

- stage: nginx_Stage

  dependsOn: []

  jobs:

  - deployment: 'software_nginx_Installation'

    environment:

      name: Dev_Environment

      resourceType: 'VirtualMachine'

      tags: nginx

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u $(app-id) -p $(secret-key) --tenant $(tanent-id)
                  key=$(az storage account keys list -g $(resource-group) -n $(storage-account-name) --query [0].value -o tsv)
                  az storage file download --share-name "geek-code" --path "server-code/01 Nginx-Host/Nginx_Install/Install_Nginx.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/01 Nginx-Host/Nginx_Install/Nginx_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  ls 
                  pwd
                  ./Install_Nginx.sh    
- stage: mockapi_Stage

  dependsOn: []

  jobs:

  - deployment: 'software_mockapi_Installation'

    environment:

      name: Dev_Environment

      resourceType: 'VirtualMachine'

      tags: mockapi

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u $(app-id) -p $(secret-key) --tenant $(tanent-id)
                  key=$(az storage account keys list -g $(resource-group) -n $(storage-account-name) --query [0].value -o tsv)
                  az storage file download --share-name "geek-code" --path "server-code/02 API-Host/Tomcat_Install/Install_tomcat.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/02 API-Host/Tomcat_Install/Tomcat_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  ls 
                  pwd
                  ./Install_tomcat.sh 
- stage: wms_Stage

  dependsOn: []

  jobs:

  - deployment: 'software_wms_Installation'

    environment:

      name: Dev_Environment

      resourceType: 'VirtualMachine'

      tags: wms

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u $(app-id) -p $(secret-key) --tenant $(tanent-id)
                  key=$(az storage account keys list -g $(resource-group) -n $(storage-account-name) --query [0].value -o tsv)
                  az storage file download --share-name "geek-code" --path "server-code/03 WMS-Host/Redis_Install/Install_Redis.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/03 WMS-Host/Redis_Install/Redis_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  //Tomcat Script
                  az storage file download --share-name "geek-code" --path "server-code/03 WMS-Host/Tomcat_Install/Install_tomcat.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/03 WMS-Host/Tomcat_Install/Tomcat_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  ls 
                  pwd
                  ./Install_Redis.sh
                  ./Install_tomcat.sh
- stage: rms_Stage

  dependsOn: []

  jobs:

  - deployment: 'software_rms_Installation'

    environment:

      name: Dev_Environment

      resourceType: 'VirtualMachine'

      tags: rms

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u $(app-id) -p $(secret-key) --tenant $(tanent-id)
                  key=$(az storage account keys list -g $(resource-group) -n $(storage-account-name) --query [0].value -o tsv)
                  az storage file download --share-name "geek-code" --path "server-code/04 RMS-Host/Tomcat_Install/Install_tomcat.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/04 RMS-Host/Tomcat_Install/Tomcat_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  ls 
                  pwd
                  ./Install_tomcat.sh
- stage: vapp_Stage

  dependsOn: []

  jobs:

  - deployment: 'software_vapp_Installation'

    environment:

      name: Dev_Environment

      resourceType: 'VirtualMachine'

      tags: vapp

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                  az login --service-principal -u $(app-id) -p $(secret-key) --tenant $(tanent-id)
                  key=$(az storage account keys list -g $(resource-group) -n $(storage-account-name) --query [0].value -o tsv)
                  az storage file download --share-name "geek-code" --path "server-code/05 VAPP-Host/Tomcat_Install/Install_tomcat.sh" --account-key $key --account-name $(storage-account-name) --dest .
                  az storage file download --share-name "geek-code" --path "server-code/05 VAPP-Host/Tomcat_Install/Tomcat_Install.tgz" --account-key $key --account-name $(storage-account-name) --dest .
                  ls 
                  pwd
                  ./Install_tomcat.sh   