trigger: none

pr: none 

 

name: ProdToTest-Db-Restore- $(Rev:r)

parameters: 

- name: environmentTag

  displayName: Environment

  type: string

  default: tam-9771

  values:

  - tam-9771

  - dev

   

stages:

- stage: Nginx_Server_Initialization

  dependsOn: []

  jobs:

  - deployment: 'Server_Installation'

    environment:

      name: Test_Environment

      resourceType: 'VirtualMachine'

      tags: nginx

    strategy:

      runOnce:

        deploy:

          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  ls
                  echo "hello"
                  # Update the list of packages
                  sudo apt-get update
                  # Install pre-requisite packages.
                  sudo apt-get install -y wget apt-transport-https software-properties-common
                  # Download the Microsoft repository GPG keys
                  wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
                  # Register the Microsoft repository GPG keys
                  sudo dpkg -i packages-microsoft-prod.deb
                  # Update the list of packages after we added packages.microsoft.com
                  sudo apt-get update
                  # Install PowerShell
                  sudo apt-get install -y powershell
                  # Start PowerShell
                  pwsh &
            - task: PowerShell@2

              displayName: 'Software_installation_on_Nginx'

              inputs:
                
                targetType: 'inline'

                script: |

                    Set-AzCurrentStorageAccount -ResourceGroupName "utkarsh-rg" -AccountName "storageaccountgeekplus"
                    Get-AzStorageFileContent -ShareName "geekplus" -Path "nginx/test.json" 
                    Write-Host "Database has been restored successfully."
                  
            - task: AzurePowerShell@5
              inputs:
                azureSubscription: 'ServiceConnection'
                ScriptType: 'InlineScript'
                Inline: |
                    Set-AzCurrentStorageAccount -ResourceGroupName "utkarsh-rg" -AccountName "storageaccountgeekplus"
                    Get-AzStorageFileContent -ShareName "geekplus" -Path "nginx/test.json" 
                    Write-Host "Database has been restored successfully."
                azurePowerShellVersion: 'LatestVersion'
                 

